language: go
go:
- 1.11
install:
- curl -LO https://github.com/gohugoio/hugo/releases/download/v0.55.4/hugo_0.55.4_Linux-64bit.deb
- sudo dpkg -i hugo_0.55.4_Linux-64bit.deb
script:
- hugo version
- hugo
addons:
  ssh_known_hosts: "${DEPLOY_HOST}"
before_install:
- openssl aes-256-cbc -K $encrypted_29d5275cc0c9_key -iv $encrypted_29d5275cc0c9_iv
  -in id_rsa_blog.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- scp  -P ${DEPLOY_PORT} -r public ${DEPLOY_USER}@${DEPLOY_HOST}:~
- ssh -p ${DEPLOY_PORT}  ${DEPLOY_USER}@${DEPLOY_HOST} './deploy_blog.sh'
env:
  global:
  - PRODUCTION=true
  - secure: s9GuCTcGoEPTfd1Zch60IiBccXcsk8ef2aeS1Ez6kpfYXLInUeR6mVIJgb/eXZPK2zg8rXCgpKKm3XP05gA0xGY/acU3JOl5pqTn1HoKPg/mWu+M0Y6LraLOGJP37yMRWiBZLuK6k95ZyiDN4Rh88vo+l4rMe3jR0hboeQkssIcO9cpmgdIwePwZH4r4RxhVpPuy7GojoSZyZxmnYKwO3o2rnCiMMQ6H6NSrBglBem7dnlnNEqo8xD1uv9DSQcHQ+GYGOkwqn7ZwSG2hIVxZZQOVdkL44pVXp02iOE+GHMsI26zXWerSJKtX+Zeqq3MGpWc8tFRvcl8u571ZXWcU+/R8DZyjTi8w4vsL2MO8ktDRTce5RhHvZxt9/v1MPQcRdlJvce7OoBKV3BOXdocS4VnxE24eahqrZYf9cyhNP8JHcb2hayQ8I5+y0Sl7fIHDAiPjBPfIySFfPur6ItGDl/RM/+eGgjfApcQe8KPDEBqIBjQ5ZYM/SiqegIT2Pq1cgu2xUEJZjXlYWS0zroZbGT6uvFeTZyfjLLnfTP49iO17ejXMvd4rQHaZyeTKinam1lN8UTq4k3YNQd/zQbxrVOQqALdV8jW3O880jD9saq4MTi4cpwGBm5TAfvacHOi0PKBMGX5CLbVzj+umsBQNYk2VTjXmP22RKnqsrStztuM=
  - secure: q4GrMJYAw7G74G45bMhScQAcEFxHNrrWHpQ3NRB/9PN6gHajsVRCV8Q8FiQCY13y/6A5hkTck6LcgFbyJFaWjGyeMsJvIltrldDvR6I2PT+5niTKRM1PxByPyiVsYYsEIG8AeJgY3Ps8XCYhdwkkHWzgeKluwO44HG3KIKab50SG+VejkMr7Xd/uIydKX7iw8973n4EdMm4MCyJUYWgzr6ullSZwR0AjpKJTNslzrElVYyqxKSvTmoxvbQOHxX1n4YXbf/U17FfQ7XfpKVedjix1PAe+A0PANZ+Ne0YTa31xi7UGkS5nIl8qMEvvQznPeCQsjxkJvMJ9cVMiWI5RHp6x0KpRqPCFbjnDaSnUZBUgW6Cv65cQ5icxtGBhg/LPTmCWfOGVLlbtHA8RyRLGhrxx88+6vr+2euIatYdV9xmxG1VT9vDGT7bFoP13K+YQ2ZaKHEQuENOpAMMemcDFklTJgRaOh0FUa/xqtvB3k8ZUVIjZEG4BqsmbvNj/wW4K3QIJAcKDUGd3Pr+vtAWQm+zzP0ZBZyPomUd1ZP9iM330mGuVa1J1GJiz37q///k/e4W737fUBdQ1USb2JPQ4izwStOKrRityVOmedxXKKPJtr7hQs7uXgg/OYFPjsAlXykVcQ2nYPBFH55gSTZjj9LEWEzn/NdJmoQHpqg9569U=
  - secure: lBYM4fbruUjIC8i7ehA4+U4hHG1qK3ZjEXaPW4mY+b75syqVjuXTaVUwTBDudayLd2ASMrd5QU08YcemsFU34dGn0u5HpWpyj9lkusNxnfvwirlFxtpLVpdY0/NZI9rL2/Awl2+GAzSEJ/UApM0gOWaItbQ1WdIG+8/t4KUNwnXltSE/sT9Lx21cgY3p99ihzSAA93M7AiV90hfqAyOpO4n72LOPtskupxEPLQ02ui36Rf7Gn36e9avPc3NfJhr+cByh+nuHY3m3k928RXz55ZLUratDzC7ALGIu3FCYKxcrehgL/tM2DRgeKyMDHPXYPV5Fxp40KN7OLrOJZQa9bJg7B7a0u7tq/gbKDfz5S5YcAX2Gj3pKJMILDGiKGHO4hPQYoOxgYL6QbqQmGSMd6MMo33AWjmc+n3jbSU5zW0yMkft39sy7kMXHLLnDhKLY696udH5m+qreez4e63wJMzk4NWqrPGkjmki/bpBkhmY5OFr2K30xR0HqlU6InsBndzn5lZlTIedUvqcj+36FD3dMGimB8sQQo0zPpz8ms3AWtBWDLd+quIB1NZFdO7Cppcy/lQonncSTsZjLGFJCEXa4zYNM/eC9TWbq9NC+TzC6UnNhjzO4WsFqScN2LMJThGFiVgzv1nSVV6z5381aA5ienPXc3SYRN7j80MzEStg=
