# baseURL = "http://localhost"
languageCode = "cn-Hans"
# title = "My New Hugo Site"

baseurl = "http://localhost"
title = "Meowu's Blog"
sub_title = "Meowu's Blog"
theme = "aglaus"

## googleAnalytics = "UA-XXXXXXXX-XX" # Optional

[params]
  dateformat = "Jan 2, 2006" # Optional
  latestSize = 4 # Optional
  ampscripts = """
<script async custom-element="amp-twitter" src="https://cdn.ampproject.org/v0/amp-twitter-0.1.js"></script>
<script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>
<script async custom-element="amp-ad" src="https://cdn.ampproject.org/v0/amp-ad-0.1.js"></script>
"""