baseURL = "https://fullstackbb.com/"
languageCode = "en-us"
title = "Meowu's Blog"
theme = "yinyang"
DefaultContentLanguage = "cn"

googleAnalytics = "UA-120601047-1" # Optional

[author]
  name = "Meowu"
  homepage = "https://fullstackbb.com/"

[languages]
  [languages.cn]
    contentDir = "content/"
    languageName = "Chinese"
    weight = 2

[params]
# disqus = "Meowu" # disqus account name
  bio = 'Saying more with fewer words.'
  extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-120601047-1"></script>'
  tags = ['front end', 'full stack engineer', 'react', 'vue', 'technology insides', 'thought works']
[[params.socials]]
name = "About Me"
link = "https://fullstackbb.com"
[[params.socials]]
name = "Github"
link = "https://github.com/meowu"
